
Neos:
  Neos:
    userInterface:
      editPreviewModes:
        # based on most used device 2020
        # https://gs.statcounter.com/screen-resolution-stats/all/europe
        tablet:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Tablet'
          width: 768px
          height: 1024px
        mobile:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Mobile'
          width: 360px
          height: 640px

##
# Alternatively use this to disable all other modes
# and only offer in-place editing
##
# Neos:
#   Neos:
#     userInterface:
#       editPreviewModes:
#         rawContent: ~
#         desktop: ~
